[package]
name = "PA-MOD-SCR"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.117"
xcap = { version = "0.0.4", optional = true }

[features]
libraries = ["xcap"]