[package]
name = "PA-MOD-DDOS"
version = "0.1.0"
edition = "2021"

[dependencies]
pnet = "0.35.0"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros", "time", "sync"] }
ping = "0.2.4"